spring:
  application:
    name: main-service
  config:
    import: "optional:configserver:"
  datasource:
    username: user
    password: psw
    url: jdbc:postgresql://localhost:5432/tasksoft_db
  jpa:
    hibernate:
      ddl-auto: validate #it was update before
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
  cloud:
    stream:
      bindings:
        taskEvents-out-0:
          destination: task-events-exchange

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5


